### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by esskar** [jchristn/DatabaseWrapper#13]
Hi,

thanks for the great library. Any plans to go full async/await?

Cheers,
Sascha

**Comment by jchristn** [comment]
Hi @esskar many thanks for the compliments and support!  I was not aware of async/await support in the various SQL client libraries that this library uses (with the exception of Sqlite).  I will look into it!

**Comment by jchristn** [comment]
Hi @esskar I am very sorry for the delay.  I finally got around to adding async support and published v6.0.0 to NuGet.

NuGet: https://www.nuget.org/packages/DatabaseWrapper/6.0.0
Commit: https://github.com/jchristn/DatabaseWrapper/commit/818a8b48a06ebfc1854a7e48ac513a1e0324ec7e

Please re-open if you use it and encounter any issues.  Cheers, Joel
