### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by MilosR** [jchristn/DatabaseWrapper#14]
Looks like some characters are not supported for Data type nvarchar. I am using latest version of WatsonORM with MySql.

For example cyrilic (Ш,Ћ,Ж), or Serbian latin, eg. Š,Ć,Ž. Or am I missing something? I see in tests that you added letter "é", I guess to test unicode, this letter works, however.

https://github.com/jchristn/DatabaseWrapper/blob/47156e5f291436b40ff3632bd218ac89f6331927/src/Test.Mysql/Program.cs#L225

**Comment by jchristn** [comment]
Hi @MilosR I'm very sorry it took me forever to get to this.  I just tried using the Test.Mysql project in DatabaseWrapper, after amending the line above with:
```
d.Add("lastname", "lastШЋЖŠĆŽ" + i);
```
And it seems to work:
![image](https://user-images.githubusercontent.com/1421081/218550663-559e337e-650f-4683-b42d-a12d65c62a4f.png)
