### ISSUE TITLE
Postgresql database access problem

### ISSUE THREAD

**Issue by rinkusahu1** [jchristn/DatabaseWrapper#15]
Hi Joel,
It just a great library I came across.
I was trying to use gatekeeper nuget package for postgresql database. Did required changes to support it. I was getting a following error.
![image](https://user-images.githubusercontent.com/37232166/216338479-5ed0938a-1a3a-43e3-a293-00471731ac63.png)

In following scenario I reproduced it
1. Ran GateKeeperConsole  project
2. first time it is running properly and creating all required table in database
3. during second time execution, it is giving above error
I think it is trying to get table information from database, during that time we are getting error.
function LoadTableColumnsQuery from  DatabaseWrapper.Postgresql/PostgresqlHelper.cs  class had hardcode test value. It should be like ***** "FROM " + database + ".INFORMATION_SCHEMA.COLUMNS cols " + ****
![image](https://user-images.githubusercontent.com/37232166/216339879-7d74611b-4122-4251-8009-d32409e45485.png)

Could you please do this changes?

**Comment by jchristn** [comment]
Fixed in DatabaseWrapper v5.0.2 (NuGet: https://www.nuget.org/packages/DatabaseWrapper/5.0.2, commit: https://github.com/jchristn/DatabaseWrapper/commit/f93176a89653fd39c29cd243d8ffcd25606db811).  Moving onto WatsonORM for dependency update, will report back.

**Comment by jchristn** [comment]
Fixed in v2.1.2 of Watson.ORM.Postgresql: https://www.nuget.org/packages/WatsonORM.Postgresql

Please re-open if any issues!

**Comment by rinkusahu1** [comment]
Thank you for doing the changes in a very short time.
