### ISSUE TITLE
Support for different SqlServer Schema (currently only able to get .dbo.* work)

### ISSUE THREAD

**Issue by treyhay31** [jchristn/DatabaseWrapper#3]
```C#
using (var client = new DatabaseClient(DbTypes.SqlServer, database: "MyDb")) 
{
  var dboQueryResult = client.Select(tableName: "Users", returnFields: new List<string> { "UserName"}); //Works and returns UserNames!

  var mySchemaQueryResult = client.Select(tableName: "mySchema.Users", returnFields: new List<string> { "UserName"}); //Fails and throws an error!
}
```

I want to get data from a table `db.mySchema.Users` and am getting an error when I include the schema in the tableName parameter for the `DatabaseClient.Select()` method. 
```
System.Data.SqlClient.SqlException: 'Invalid object name 'mySchema.Users'.'
```
I don't see another place to specify schema but maybe I need to look harder? Does this functionality exist? If not, can you point me to the area of the code where it might be possible and I will send you a pull request?

**Comment by jchristn** [comment]
Hi @treyhay31 is the user with which you are connecting configured with the appropriate privileges to access the specified schema?  Or perhaps the user is mapped to the ```mySchema``` schema already?

I am not aware of a simple way to specify a schema when using ```SqlConnection```.  What I've found is that the queries have to be built using the schema as part of the table names, so your usage above should be correct (i.e. ```mySchema.Users```.

In the SELECT query builder, I'm encapsulating the table name into ```[``` followed by ```]```.  Could you try setting your table name to ```mySchema].[Users``` and see if that makes a difference?  Yes, it's a hack :) but if that works, I can think through how to best amend the library to take a schema name into account.

**Comment by jchristn** [comment]
BTW I just tested this in my test project and it appeared to work.  I have a database called ```test``` with a schema called ```foo``` and a table called ```colors```.
```
[DatabaseWrapper.SqlServer] query: SELECT *  FROM [foo].[colors] WHERE ([id] > 0)
[DatabaseWrapper.SqlServer] result: 14 rows
```
```
Expression eFoo = new Expression("id", Operators.GreaterThan, 0);
DataTable foo = _Database.Select("foo].[colors", null, null, null, eFoo);
```

I used the hack I mentioned above and it worked.  I'll see if I can amend the library to have a separate schema parameter so that you don't have to use it this way.

**Comment by jchristn** [comment]
I just updated the DatabaseWrapper.SqlServer package: https://www.nuget.org/packages/DatabaseWrapper.SqlServer/3.2.2.11

Could you try this one?  You should just be able to do ```schema.table```.  If this works, I'll update the main DatabaseWrapper package and also find a way to integrate for PostgreSQL (in MySQL the database and schema are synonymous, and in Sqlite, there isn't such a concept).

**Comment by treyhay31** [comment]
Ha! You are awesome! Just like that, my dreams have come true. Thank you.
