### ISSUE TITLE
Connect to SQL Server without using user credentials

### ISSUE THREAD

**Issue by igrgurina** [jchristn/DatabaseWrapper#6]
Is there a way to construct DatabaseClient using the connection string in the form of: 
```sql
Data Source=DESKTOP;Initial Catalog=X1;Integrated Security=True
```
That's using localhost default port **Windows Authentication**. The examples all use user credentials.

**Comment by igrgurina** [comment]
Ok, I figured out from the code how to do it: 

```csharp
DatabaseClient _client = new DatabaseClient(new DatabaseSettings(DbTypes.SqlServer, [dataSource], [defaultPort], null, null, [initialCatalogue]));
```

I'm going to close this issue, but maybe it's a good idea adding one line like this to the README. Thanks for all your great work!

**Comment by igrgurina** [comment]
I'm reopening this because it doesn't work. `DatabaseSettings` constructor has a `throw new ArgumentNullException(nameof (username));`.

**Comment by jchristn** [comment]
Hi @igrgurina just checked, the connection string builders are (as is) ok with null for usernames and passwords, but as you rightly pointed out, the ```DatabaseSettings``` constructor is not.  I'll patch this now.

**Comment by jchristn** [comment]
Commit: https://github.com/jchristn/DatabaseWrapper/commit/3bf7c55a22094e54f294c70c64e91a452e20f7fc
Nuget packages updated, please re-open if any issues.  Thank you for the suggestion!

**Comment by igrgurina** [comment]
Works great, thank you!
